version: '3'

services:

  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wp_data:/var/www/html
      - ".:/var/www/html/wp-content/plugins/signin-with-apple:ro" # Without "ro" flags it can't access the directory.
    restart: always
    environment:
      WORDPRESS_DEBUG: 1

  wpcli:
    image: wordpress:cli
    depends_on:
      - mysql
      - wordpress
    volumes:
      - wp_data:/var/www/html
    command: wp core install --url=signinwithapple.local --title="Sign In with Apple Plugin" --admin_user=admin --admin_password=password --admin_email=admin@example.com --path=/var/www/html

volumes:
  db_data: {}
  wp_data: {}
